### ISSUE TITLE
테스트용 MintFoodAction에서 InvalidBlockStateRootHashException

### ISSUE THREAD

**Issue by eseiker** [eseiker/Savor-22b#1]
https://github.com/eseiker/Savor-22b/tree/asdf

```
[16:55:49 INF] [ActionEvaluator] Action Savor22b.Action.MintFoodAction took 0 ms to execute, GetState called 2 times and took 0 ms
[16:55:49 INF] [ActionEvaluator] Took 0 ms to evaluate 1 actions ["MintFoodAction"] in transaction f05818149c58b22a29cd2ae158032727b1734e72a69003a43d176ee66cc9a57a by 0x53103C2D7875D2f5f02AeC3075155e268a6e3A94 as a part of block #122 pre-evaluation hash 9c0c2a67a9a644f398847fa69614651d0058ec988309bddd66e6785aad040dec
[16:55:49 INF] [ActionEvaluator] Actions in 1 transactions for block #122 pre-evaluation hash 9c0c2a67a9a644f398847fa69614651d0058ec988309bddd66e6785aad040dec evaluated in 1 ms
[16:55:49 DBG] [BlockChain] Took 1 ms to summarize the states delta with 2 key changes made by block #122 pre-evaluation hash 9c0c2a67a9a644f398847fa69614651d0058ec988309bddd66e6785aad040dec
[16:55:49 INF] [BlockChain] Took 2 ms to update the states with 2 key changes and resulting in state root hash 387b98bcde0d010f178665e43dedb8e3cf9160d5370300d36d791e26557907b1 for block #122 pre-evaluation hash 9c0c2a67a9a644f398847fa69614651d0058ec988309bddd66e6785aad040dec
[16:55:49 DBG] [Context] Block #122 db9a8b685e986d1523e718c9a1a92dc67d9a1f83477066d8f186c1a7950e083f is invalid
Libplanet.Blocks.InvalidBlockStateRootHashException: Block #122 db9a8b685e986d1523e718c9a1a92dc67d9a1f83477066d8f186c1a7950e083f's state root hash is ba756bcbddcff8274ece02ccd83c4ac3dac43a394dda7c822e5a1e6fe6fe9042, but the execution result is 387b98bcde0d010f178665e43dedb8e3cf9160d5370300d36d791e26557907b1.
   at Libplanet.Blockchain.BlockChain.ValidateBlockStateRootHash(Block block, IReadOnlyList`1& evaluations)
   at Libplanet.Net.Consensus.Context.IsValid(Block block, IReadOnlyList`1& evaluatedActions)
```

**Comment by sonohoshi** [comment]
이거 로컬에서 띄워서 돌린거에요?

**Comment by eseiker** [comment]
넹

**Comment by sonohoshi** [comment]
https://github.com/eseiker/Savor-22b/commit/1d36b14f8503cbc5b0ae5e09bd6c77ffa5802a10#diff-9f2baf9f2a985bc78c9a6df5bd52611b3b3e378dabd5714712d5f2ef5f52d906R47
`Guid.NewGuid`
